#!/bin/bash

arch=$(echo $0 | cut -d- -f2)

su -l ${GITLAB_CI_USER} -p -c \
  "${GITLAB_CI_RUNNER_PATH} register
  --config ${GITLAB_CI_CONFIG}
  --non-interactive
  --description \"GitLab CI runner for ${arch}\"
  --executor docker
  --docker-image laarid/devel:${arch}
  $@"
